### ISSUE TITLE
Domain Architecture not printing in the order of the N- to C-term direction

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/CoDIAC#11]
#### Description
Uniprot makeRefFile appears to have the correct domain architecture pieces, but they are not printing in the order as they are seen in the protein. 

#### Screenshots
Uploaded an example of the domain architecture printed for the two PI3K proteins, which should match. A screenshot of the architecture in ProteomeScout confirms that for at least PI3KR2 the order is incorrect. 

#### Expected behavior
The domains need to be sorted by their start position, then a string created in the order that they appear by start, such that the first domain in the list appears first, then the second, and so forth. With incoming code on handling domain boundaries, we can assume that domains will not be overlapping.

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at, if known
- [x] Update code to fix
- [x] Test and validate on several protein families with multdomain architectures.
- [x] Rerun the code to get the reference file (Kristen)
