### ISSUE TITLE
Integrate InterPro Domain

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/CoDIAC#13]
**Is your feature request related to a problem? Please describe.**
Adding InterPro domains to reference file for use, we are partway there and these are the tasks remaining. 

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Correct the Intepro domain Boundaries to print like domains. Current string example: ['SH3_domain:IPR001452:4:80', 'RhoGAP_dom:IPR000198:109:295', 'SH2:IPR000980:328:425', 'PI3K_P85_iSH2:IPR032498:428:595', 'SH2:IPR000980:620:716']
- [x] Add domain architecture, based on InterPro
- [x] Update domain boundary mapping to take Uniprot or InterPro boundaries, default to Interpro.
