### ISSUE TITLE
Interpro Domain annotation, not always getting the correct level

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/CoDIAC#14]
#### Description
Noted in Interpro Domain anntoation, that some superfamily domains are missed, and instead we get multiple overlapping subdomains. 

#### Screenshots
<img width="924" alt="Screen Shot 2023-07-06 at 11 54 38 AM" src="https://github.com/NaegleLab/CoDAC/assets/3899636/735a108e-32f2-4581-86d7-ee1c9f64d11e">

#### Files
Currently in annotation we are getting the subdomains Tyr_Pase_cat and Tyr_Pase_dom, but not the larger domain of interest. 

#### Expected behavior
Desired behavior is to return just the PTP_cat domain with boundaries of 246-523.

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at, if known
- [x] Define the issue in terms of how best to identify that family, and increase coherency in domain annotations
- [x] Update the code
- [x] Rerun annotations of reference
- [x] Manual alterations with documentation of final reference
- [x] Rerun structure merge with reference
- [x] Make the new reference Fasta and alignments, retranslate features based on the new reference.
