### ISSUE TITLE
Seeing overlapping domains in InterPro annotations

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/CoDIAC#15]
#### Description
Despite boundary harmonization in InterPro annotation of the human reference file, we are seeing some domains that overlap. 

#### Examples
Examples include:
VAV1 (P15498) - we get a VAV1_SH3 domain that overlaps with an SH3 domain 
TNS4 (Q8IZW8) - we see a PTB/PI_dom that overlaps with a PTB domain

#### Expected behavior
Desired behavior is to have only the universal domain annotation (i.e. SH3 and PTB) in these cases on the domain list and the architecture list.

#### Tasks
- [x] Determine why boundary collapse is missing these cases
- [x] Update the code
- [x] Update the reference and subsequent files.
