### ISSUE TITLE
Improve other species fetch of InterPro records

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/CoDIAC#17]
**Is your feature request related to a problem? Please describe.**
Currently, default Interpro fetch of Uniprot records containing an InterPro domain is rigid and only returns reviewed records, meaning that only very well studied organisms will return records (e.g. for SH2 470 proteins out of 136K possible). We would like to give users the ability to accept unreviewed records and to query specific taxonomies. 

**Describe the solution you'd like**
Add the capability to query taxonomy (i.e. get information about domains in different taxa)
Add the capability to turn on or off the Reviewed flag
Add the capability to return records based on taxonomy id or to get all records at once.

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Understand and add the REVIEWED flag to fetch
- [x] Add taxonomy handling (including checking for taxon incorrect)
- [x] Add feature to return info about taxonomy from a direct taxonomy fetch of InterPro
