### ISSUE TITLE
Update PDB reference column names

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/CoDIAC#25]
#### Description
The PDB columns that are really important are hard to understand from the titles, and they are misspelled (cannonical instead of canonical, but canonical as a phrase is unclear in this context). Hence, let's take this opportunity to identify a better way to refer to what is currently: CANNONICAL_REF_SEQ and CANNONICAL_SEQ_BEG_POSITION

#### Files
PDB reference file and derivatives.

#### Expected behavior
PDB_SEQ - sequence of the PDB
UNIPROT_SEQ - sequence of the reference (Uniprot) - **let's change this to REF_SEQ**
CANNONICAL_REF_SEQ - let's change this to PDB_REF_SEQ (i.e. the intersection of PDB and REF seq)
PDB_SEQ_BEG_POSITION - can keep this the same
CANNONICAL_SEQ_BEG_POSITION - **let's change this to REF_SEQ_BEG_POSITION**

#### Tasks
- [x] Change the PDB generator to rename these columns. 
- [x] Update dependent code in the integration and anywhere else these columns are used
- [x] Update the References.md documentation
- [x] Update the figure that References.md uses (@knaegle will have to do this).
