### ISSUE TITLE
Interpro Helper - updates for improving interactions

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/CoDIAC#3]
**Is your feature request related to a problem? Please describe.**
Notes from development of features on how Uniprot should work

**Describe the solution you'd like**
We would like this to be a standalone helper that gives us information about Uniprot IDs as a CSV file, generally readable, but also used in CoDAC for mapping regions of interest in structures. 

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Make a single helpers.UniProt.makeReferenceFile - this will produce CSV a list of uniprot ids. Add outputfile as an argument of where this data is going.
- [x] Add a uniprot column to the reference file output that includes species.
- [x] Remove fasta file production from here, with intent to allow reference fasta production in relevant class.

**Additional context**
