### ISSUE TITLE
Use consistent headers in PDB metadata file

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/CoDIAC#34]
**Is your feature request related to a problem? Please describe.**
Related to Ticket #25 there is confusion in the naming conventions. Update the column names to match closely with the rcsb data fields, this will assist users in being able to find more information about these fields. 

**Describe the solution you'd like**
[PDB_column_fixes.csv](https://github.com/NaegleLab/CoDIAC/files/12563588/PDB_column_fixes.csv)

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Make the headers global as a list (currently split in two places in PDB file)
- [x] Replace the names of headers in PDB
- [x] Update other front end software - Integration (@knaegle)
- [x] Update the documentation
- [x] #39

**Additional context**
