### ISSUE TITLE
Integration feature and bug fixes

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/CoDIAC#35]
#### Description
Integration of PDB and Uniprot currently works for the most part. However there are a series of bugs and requested features

#### Screenshots
See Ticket #27 about mutation issues

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at, if known
- [x] Update integration column names to be clear they come from the reference integration. We decided that all of these column names will begin with IntRef:
- [x] See and resolve Ticket #27 about differences in mutation data.
- [x] For entities not found in the reference file, we want to still report the sequence (using pdbx_seq_one_letter_code_can and setting the reference range to be 1-rcsb_sample_sequence_length+1)
- [x] 'reference range' and 'struct/ref sequence' columns have empty cells for structures that do not have a reference available (like ligands). Replace these empty cells with 'not found'.  --- ignored, this was fixed in another ticket by copying the sequence and designating range where record is not in reference. All other fields are N/A
