### ISSUE TITLE
Need to modify CoDIAC to accommodate small molecule entities

### ISSUE THREAD

**Issue by juliannahitchcock00** [NaegleLab/CoDIAC#44]
**Feature**
I am attempting to utilize CoDIAC for protein domains that bind to other entities besides peptides, such as small molecule entities. For example, I am hoping to analyze the binding of PH domain-containing proteins. However, PH domains bind phosphoinositides, which are phospho**lipid**s in cell membranes. These non-polymer entities are not currently included by CoDIAC.

To address this issue, I would like to ensure that CoDIAC can work with all small molecule entities. I would like any necessary changes and/or additions to be made.

#### Tasks
- [ ] Include non-polymer entities in PDB.py & PDB files produced from domain_setup.ipynb files @juliannahitchcock00 
- [ ] Modify adjacency files to accommodate small molecule entities @alekhyaa2 
- [ ] Test modified pipeline using an example domain, such as the PH domain @juliannahitchcock00 
- [ ] Implement if possible
