### ISSUE TITLE
Add annotation to map between the Uniprot Reference and Structure Reference and CIF experimental sequence numbers

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/CoDIAC#6]
**Is your feature request related to a problem? Please describe.**
Develop (from pieces in our dev environment) the check between a Uniprot reference file (CSV) and the structure reference file and the Arpeggio generated contact maps, to find the offsets (if any) in the numbering of files. Additionally, this annotation will denote the regions/domains spanned in a Unprot protein by the structure that was experimentally performed. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Add annotation to StructureRefFile of UniprotRefFile regions spanned by the structure (i.e. domains inclusive, mutations)
- [x] Add to PDB (helper) the CIF file get for structures (takes an Uniprot_ann_structureFile, which may have been filtered at some step by someone to reduce to relevant structures covering domains of interest)
- [x] Add annotation to the structure reference file to account for CIF-based residue numbering (which is known from adjacency files), which may differ from reference (i.e. offset)

**Additional context**
