### ISSUE TITLE
Speed up Uniprot Fetch by getting all information from the same record fetch

### ISSUE THREAD

**Issue by knaegle** [NaegleLab/CoDIAC#8]
**Is your feature request related to a problem? Please describe.**
Currently, CoDAC.Uniprot fetch to uniprot information takes a very long time as the architecture is setup to do a new URL fetch/query for each piece of information. 

**Describe the solution you'd like**
Fetch all relevant information from the Uniprot Record at the time of a record fetch. 

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Collapse all information grabs for the Uniprot object into one fetch 
- [x] Replace the Domains and domain architecture fields with new code that mixes InterPro/UniProt decision
- [x] Instead of fetching records again for PDB IDs, add a column to the makeRefFile that is PDB IDs, ID values that are semicolon separated. We can parse these then later without fetching Uniprot records again for PDB parsing.
